/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/alive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 稼働かどうかを判定 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 稼働中である．文字列は指定されない */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /** @example ok */
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/faculties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 学部・専攻一覧の取得
         * @description 学部とその専攻を返す
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 学部とその専攻の一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example [
                         *       {
                         *         "id": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
                         *         "name": "工学部",
                         *         "majors": [
                         *           {
                         *             "id": "550e8400-e29b-41d4-a716-446655440000",
                         *             "name": "情電数理系/情報工学コース"
                         *           },
                         *           {
                         *             "id": "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
                         *             "name": "情電数理系/ネットワーク工学コース"
                         *           }
                         *         ]
                         *       },
                         *       {
                         *         "id": "6ba7b812-9dad-11d1-80b4-00c04fd430c8",
                         *         "name": "理学部",
                         *         "majors": [
                         *           {
                         *             "id": "6ba7b813-9dad-11d1-80b4-00c04fd430c8",
                         *             "name": "数学科"
                         *           },
                         *           {
                         *             "id": "6ba7b814-9dad-11d1-80b4-00c04fd430c8",
                         *             "name": "物理学科"
                         *           }
                         *         ]
                         *       }
                         *     ]
                         */
                        "application/json": components["schemas"]["Faculty"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 科目候補の取得
         * @description 指定した分類で絞り込んだ科目の候補を返す
         */
        get: {
            parameters: {
                query: {
                    /** @description 学部のUUID */
                    faculty: string;
                    /** @description 専攻のUUID(指定したfacultyに属するmajorのid) */
                    major?: string;
                    /** @description テストが行われる学年 */
                    grade?: number;
                    /** @description 学期 */
                    term?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 条件に合致する科目の一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example [
                         *       {
                         *         "id": "9b2e4c6a-1f3d-4e5b-8a7c-0d1e2f3a4b5c",
                         *         "name": "線形代数",
                         *         "faculty": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
                         *         "major": "550e8400-e29b-41d4-a716-446655440000",
                         *         "grade": 1,
                         *         "term": 1
                         *       },
                         *       {
                         *         "id": "a1b2c3d4-e5f6-4a5b-9c8d-7e6f5a4b3c2d",
                         *         "name": "アルゴリズムと計算量",
                         *         "faculty": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
                         *         "major": "550e8400-e29b-41d4-a716-446655440000",
                         *         "grade": 2,
                         *         "term": 2
                         *       }
                         *     ]
                         */
                        "application/json": components["schemas"]["Subject"][];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ファイルとメタデータのアップロード
         * @description サーバ側で検証すべきこと
         *
         *     - サイズ: 1ファイルあたり100MBまで
         *     - 許可される形式:
         *       - 画像(jpg, jpe, jpeg, webp, png)
         *       - ドキュメント(doc, docx, pdf)
         *       - プレーンテキスト(txt)
         *       - マークアップ(md, typ, tex)
         *
         *     アップロード者はCloudflare Accessの認証情報から記録する
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        files: string[];
                        metadata: components["schemas"]["DocumentMetadata"];
                    };
                };
            };
            responses: {
                /** @description アップロード成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                /** @description ファイルサイズが上限を超過 */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "message": "file size exceeds the limit of 100MB per file",
                         *       "details": "uploaded file size: {}MB. must <= 100MB"
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 許可されていないファイル種別 */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "message": "allowed: jpg, jpeg, jpe, webp, png, doc, docx, pdf, txt, md, typ, tex",
                         *       "details": "uploaded type: {}."
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 学部とそれに属する専攻
         * @example {
         *       "id": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
         *       "name": "工学部",
         *       "majors": [
         *         {
         *           "id": "550e8400-e29b-41d4-a716-446655440000",
         *           "name": "情電数理系/情報工学コース"
         *         },
         *         {
         *           "id": "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
         *           "name": "情電数理系/ネットワーク工学コース"
         *         }
         *       ]
         *     }
         */
        Faculty: {
            /**
             * Format: uuid
             * @description 学部のUUID
             */
            id: string;
            /**
             * @description 学部名
             * @example 工学部
             */
            name: string;
            /** @description この学部に属する専攻の一覧 */
            majors: components["schemas"]["Major"][];
        };
        /**
         * @description 専攻等
         * @example {
         *       "id": "550e8400-e29b-41d4-a716-446655440000",
         *       "name": "情電数理系/情報工学コース"
         *     }
         */
        Major: {
            /**
             * Format: uuid
             * @description 専攻のUUID
             */
            id: string;
            /**
             * @description 専攻名
             * @example 情電数理系/情報工学コース
             */
            name: string;
        };
        /**
         * @description 科目が持つべき情報
         *     同名でも faculty / major / grade / term が異なれば別科目
         * @example {
         *       "id": "9b2e4c6a-1f3d-4e5b-8a7c-0d1e2f3a4b5c",
         *       "name": "線形代数",
         *       "faculty": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
         *       "major": "550e8400-e29b-41d4-a716-446655440000",
         *       "grade": 1,
         *       "term": 1
         *     }
         */
        Subject: {
            /**
             * Format: uuid
             * @description 科目のUUID
             */
            id: string;
            /**
             * @description 科目名
             * @example 線形代数
             * @example アルゴリズムと計算量
             */
            name: string;
            /**
             * Format: uuid
             * @description 学部のUUID
             */
            faculty: string;
            /**
             * Format: uuid
             * @description 専攻のUUID
             */
            major: string;
            /**
             * @description テストが行われる学年
             * @example 1
             */
            grade: number;
            /**
             * @description 学期
             * @example 1
             */
            term: number;
        };
        /**
         * @description 試験種別
         * @enum {string}
         */
        ExamType: "quiz" | "midterm" | "final" | "other";
        /**
         * @example {
         *       "faculty": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
         *       "major": "550e8400-e29b-41d4-a716-446655440000",
         *       "year": 2025,
         *       "term": 2,
         *       "grade": 2,
         *       "subject": "9b2e4c6a-1f3d-4e5b-8a7c-0d1e2f3a4b5c",
         *       "teacher": "岡山 聖彦",
         *       "examtype": "final",
         *       "isanswer": false,
         *       "num": 1
         *     }
         */
        DocumentMetadata: {
            /**
             * Format: uuid
             * @description 学部のUUID
             */
            faculty: string;
            /**
             * Format: uuid
             * @description 専攻等のUUID(指定したfacultyに属するmajorのid)
             */
            major: string;
            /**
             * @description 西暦
             * @example 2026
             */
            year: number;
            /**
             * @description 学期
             * @example 2
             */
            term: number;
            /**
             * @description テストが行われる学年
             * @example 1
             */
            grade: number;
            /**
             * Format: uuid
             * @description 科目のUUID(指定したfaculty/major/grade/termに属するsubjectのid)
             */
            subject: string;
            /**
             * @description 教員名
             * @example 岡山 聖彦
             */
            teacher: string;
            examtype: components["schemas"]["ExamType"];
            /** @description 解答かどうか */
            isanswer: boolean;
            /**
             * @description 何番目の試験か
             * @example 1
             * @example 7
             */
            num: number;
        };
        /**
         * @example {
         *       "message": "unexpected error occurred",
         *       "details": "please try again later"
         *     }
         */
        Error: {
            /** @description 形式自由なエラーの概要 */
            message: string;
            /** @description 形式自由な追加情報 */
            details?: string;
        };
    };
    responses: {
        /** @description リクエストが不正 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "message": "missing required field",
                 *       "details": "field 'metadata.faculty' is required"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Cloudflare Accessによる認証がない，または無効 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "message": "missing or invalid Cf-Access-Jwt-Assertion"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
