/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/alive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 稼働かどうかを判定 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 稼働中である．文字列は指定されない */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /** @example ok */
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/faculties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 学部・専攻一覧の取得
         * @description 学部とその専攻を返す
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 学部とその専攻の一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Faculty"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ファイルとメタデータのアップロード
         * @description サーバ側で検証すべきこと
         *
         *     - サイズ: 1ファイルあたり100MBまで
         *     - 許可される形式:
         *       - 画像(jpg, jpe, jpeg, webp, png)
         *       - ドキュメント(doc, docx, pdf)
         *       - プレーンテキスト(txt)
         *       - マークアップ(md, typ, tex)
         *
         *     アップロード者はCloudflare Accessの認証情報から記録する
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        files: string[];
                        metadata: components["schemas"]["DocumentMetadata"];
                    };
                };
            };
            responses: {
                /** @description アップロード成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                /** @description ファイルサイズが上限を超過 */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 許可されていないファイル種別 */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 学部とそれに属する専攻 */
        Faculty: {
            /**
             * Format: uuid
             * @description 学部のUUID
             */
            id: string;
            /**
             * @description 学部名
             * @example 工学部
             */
            name: string;
            /** @description この学部に属する専攻の一覧 */
            majors: components["schemas"]["Major"][];
        };
        /** @description 専攻等 */
        Major: {
            /**
             * Format: uuid
             * @description 専攻のUUID
             */
            id: string;
            /**
             * @description 専攻名
             * @example 情報工学科
             */
            name: string;
        };
        /**
         * @description 試験種別
         * @enum {string}
         */
        ExamType: "quiz" | "midterm" | "final" | "other";
        DocumentMetadata: {
            /**
             * Format: uuid
             * @description 学部のUUID
             */
            faculty: string;
            /**
             * Format: uuid
             * @description 専攻等のUUID(指定したfacultyに属するmajorのid)
             */
            major: string;
            /**
             * @description 西暦
             * @example 2026
             */
            year: number;
            /**
             * @description 学期
             * @example 2
             */
            term: number;
            /**
             * @description テストが行われる学年
             * @example 1
             */
            grade: number;
            /**
             * @description 科目名
             * @example 線形代数
             */
            subject: string;
            /**
             * @description 教員名
             * @example 岡山 聖彦
             */
            teacher: string;
            examtype: components["schemas"]["ExamType"];
            /** @description 解答かどうか */
            isanswer: boolean;
            /**
             * @description 何番目の試験か
             * @example 1
             * @example 7
             */
            num: number;
        };
        Error: {
            /** @description 形式自由なエラーの概要 */
            message: string;
            /** @description 形式自由な追加情報 */
            details?: string;
        };
    };
    responses: {
        /** @description リクエストが不正 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Cloudflare Accessによる認証がない，または無効 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
